spring:
  application:
    name: backend
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/dbchangelog.xml

jwt:
  signing-key: ${JWT_SIGNING_KEY}
  expiration-time: 100000000000000

firebase:
  credentials: ${FIREBASE_CONFIG_JSON}

weatherApi:
  token: 5390f8d494c44cde982164605251706

hints:
  url: ${HINTS_URL:http://45.141.78.50:8800/entities/get_text_based_hint}