spring:
  application:
    name: backend
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/dbchangelog.xml

jwt:
  signing-key: ${JWT_SIGNING_KEY}
  expiration-time: 10000000

firebase:
  credentials: ${FIREBASE_CONFIG_JSON:#{null}}