name: Release

on:
  workflow_dispatch:
    inputs:
      app_version:
        description: 'Tag version for the release'
        required: true

env:
  APP_VERSION: ${{ github.event.inputs.app_version }}

jobs:

  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare docker
        uses: ./.github/actions/prepare-docker
        with:
          password: ${{ secrets.DOCKER_PASSWORD }}
          username: ${{ secrets.DOCKER_USER }}

      - name: Build Docker images
        env:
          CI_REGISTRY_IMAGE: docker.io/brawleryura1
        run: docker-compose build notes-app

      - name: List images
        run: docker images

      - name: Tag Docker images
        run: |
          docker tag docker.io/brawleryura1/notes-app:$APP_VERSION docker.io/brawleryura1/notes-app:latest

      - name: Push Docker images
        run: |
          docker push -a docker.io/brawleryura1/notes-app

      - name: Display build completion date
        run: echo "Build completed on $(date)"

  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.APP_VERSION }}
          release_name: Release ${{ env.APP_VERSION }}
          body: "New release of the application"
          draft: false
          prerelease: false

  deploy:
    runs-on: self-hosted
    needs: release
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Chmod
        run: |
          chmod +x ./deploy.sh

      - name: Deploy Docker Image
        run: ./deploy.sh
